package demo.web.dialog;

/**
 * @author Per Johansson
 */
public enum States {
    INITIAL, ROOT, ACCOUNT_DETAILS, ACCOUNTS, STATEMENT, END, STATEMENT_MONTHLY, STATEMENT_ANNUAL, STATEMENT_CHOICE, INTEREST_RATE, INTEREST_RATE_OFFER
}
